apiVersion: apps/v1
kind: Deployment
metadata:
  name: raillo-api
  namespace: api-server
spec:
  revisionHistoryLimit: 2
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: raillo-api
  template:
    metadata:
      labels:
        app: raillo-api
    spec:
      nodeSelector:
        raillo-node: app
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: raillo-api
          image: ghcr.io/penggu-dev/raillo-api:latest
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: raillo-config
            - secretRef:
                name: raillo-secrets
          env:
            - name: JDK_JAVA_OPTIONS
              value: -XX:MaxRAMPercentage=75.0
          resources:
            requests:
              cpu: 1000m
              memory: 2Gi
            limits:
              cpu: 1000m
              memory: 2Gi
          lifecycle:
            preStop:
              sleep:
                seconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
            timeoutSeconds: 60
          livenessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 20
            timeoutSeconds: 60
            failureThreshold: 3
