apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: raillo-api
  namespace: api-server
  annotations:
    cert-manager.io/cluster-issuer: raillo-issuer
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - server.raillo.site
      secretName: server-raillo-site-tls
  rules:
    - host: server.raillo.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: raillo-api
                port:
                  number: 80
