name-template: '$RESOLVED_VERSION' # 릴리즈 이름 정의. Release Drafter가 계산한 최종 버전
tag-template: '$RESOLVED_VERSION' # 릴리즈와 연결될 git 태그

categories: # 릴리즈 노트를 섹션별로 분류
  - title: '✨ 새로운 기능' # 섹션 제목
    labels:
      - '✨ feature' # PR에 붙은 라벨명
  - title: '🐛 버그 수정'
    labels:
      - '🐞 bug'
  - title: '♻️ 리팩토링'
    labels:
      - '♻️ refactor'
  - title: '그 외'
    labels:
      - '⚙️ chore'
      - '📝 docs'
      - '✅ test'
version-resolver: # 라벨별 버전 증가 규칙
  major:
    labels: # pr 라벨
      - '⭐️ major'
  minor:
    labels:
      - '⭐️ minor'
  patch:
    labels:
      - '⭐️ patch'
  default: patch # 라벨이 없으면 패치 버전 증가

exclude-labels: # 릴리즈 노트에서 제외할 라벨
  - "🚀 release"
  - "💫 revert"

change-template: "- $TITLE (#NUMBER) - @$AUTHOR" # PR 표기 템플릿.
change-title-escapes: '\\<*_&' # 특수문자 이스케이프 처리 (마크다운 깨짐 방지)

template: | # Release Drafter가 생성할 릴리즈 본문 구조 정의
  ## 변경사항

  $CHANGES 

  **Full Changelog**: $PREVIOUS_TAG...$RESOLVED_VERSION 
  
  $CONTRIBUTORS
