services:
  mysql:
    image: 'chanwon2/raillo-db-with-data'
    environment:
      - 'MYSQL_DATABASE=raillo'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=secret'
      - 'MYSQL_USER=sa'
    ports:
      - '3306:3306'
  redis:
    image: 'redis:latest'
    command: redis-server --notify-keyspace-events Ex
    ports:
      - '6379:6379'
