apiVersion: batch/v1
kind: CronJob
metadata:
  name: train-daily-schedule
  namespace: raillo
spec:
  schedule: "0 17 * * *" # KST 02:00
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: raillo-batch
              image: 052104148083.dkr.ecr.ap-northeast-2.amazonaws.com/raillo-batch:latest
              command: ["sh", "-c"]
              args:
                - >-
                  java -jar /app/app.jar
                  --spring.batch.job.name=trainDailyScheduleJob
                  run.id=$(date +%s)
              resources:
                requests:
                  cpu: "0.25"
                  memory: "256Mi"
                limits:
                  cpu: "1"
                  memory: "1Gi"
              envFrom:
                - configMapRef:
                    name: raillo-config
                - secretRef:
                    name: raillo-secrets

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: delete-expired-members
  namespace: raillo
spec:
  schedule: "0 18 * * *" # KST 03:00
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: raillo-batch
              image: 052104148083.dkr.ecr.ap-northeast-2.amazonaws.com/raillo-batch:latest
              command: ["sh", "-c"]
              args:
                - >-
                  java -jar /app/app.jar
                  --spring.batch.job.name=deleteExpiredMembersJob
                  run.id=$(date +%s)
              resources:
                requests:
                  cpu: "0.25"
                  memory: "256Mi"
                limits:
                  cpu: "1"
                  memory: "1Gi"
              envFrom:
                - configMapRef:
                    name: raillo-config
                - secretRef:
                    name: raillo-secrets
