plugins {
    id 'java-library'
    id 'java-test-fixtures'
}

dependencies {
    api 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework:spring-web'
    implementation 'com.fasterxml.jackson.core:jackson-annotations'

    testFixturesCompileOnly 'org.projectlombok:lombok'
    testFixturesAnnotationProcessor 'org.projectlombok:lombok'
}

jar {
    enabled = true
}
