apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      nodeSelector:
        raillo-node: app
      initContainers:
        - name: init-grafana-data
          image: docker.io/library/busybox:1.36.1
          command:
            - sh
            - -c
            - chown -R 472:0 /var/lib/grafana
          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana
      containers:
        - name: grafana
          image: docker.io/grafana/grafana:13.2.2
          ports:
            - name: grafana
              containerPort: 3000
          envFrom:
            - secretRef:
                name: grafana-secret
          env:
            - name: GF_SERVER_ROOT_URL
              value: https://monitoring.raillo.site
          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana
            - name: datasource
              mountPath: /etc/grafana/provisioning/datasources
            - name: dashboard-provider
              mountPath: /etc/grafana/provisioning/dashboards
            - name: dashboards
              mountPath: /etc/grafana/dashboards
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
      volumes:
        - name: grafana-data
          hostPath:
            path: /var/lib/raillo/grafana
            type: DirectoryOrCreate
        - name: datasource
          configMap:
            name: grafana-datasource
        - name: dashboard-provider
          configMap:
            name: grafana-dashboard-provider
        - name: dashboards
          projected:
            sources:
              - configMap:
                  name: grafana-dashboards
              - configMap:
                  name: grafana-dashboards-reservation
                  optional: true
