apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-exporter
  template:
    metadata:
      labels:
        app: mysql-exporter
    spec:
      nodeSelector:
        raillo-node: data
      containers:
        - name: mysql-exporter
          image: docker.io/prom/mysqld-exporter:v0.20.0
          args:
            - --mysqld.address=mysql.mysql.svc.cluster.local:3306
            - --mysqld.username=exporter
            - --collect.info_schema.processlist
          envFrom:
            - secretRef:
                name: mysql-exporter-secret
          ports:
            - name: metrics
              containerPort: 9104
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
