apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      # 노드 주소(<IP>:10250)를 node-exporter 포트로 바꿔 수집
      - job_name: node-exporter
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - source_labels: [__address__]
            regex: '(.*):10250'
            replacement: '${1}:9100'
            target_label: __address__

      - job_name: raillo-api
        metrics_path: /actuator/prometheus
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: [api-server]
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: raillo-api
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            action: keep
            regex: "8080"

      - job_name: valkey
        static_configs:
          - targets: ['valkey-exporter.monitoring.svc.cluster.local:9121']

      - job_name: mysql
        static_configs:
          - targets: ['mysql-exporter.monitoring.svc.cluster.local:9104']
