name: Release Drafter

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v7
        with:
          publish: true # push 시 항상 publish. 생성한 릴리즈 노트를 draft 상태로 둘 것인지 publish 할 것인지 결정
          commitish: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
